### ISSUE TITLE
Consider altering license to something more permissive of reuse

### ISSUE THREAD

**Issue by jthielen** [jsillin/SoundingMaps#1]
Thanks @jsillin for putting up your examples on GitHub! Hopefully they can help be good starting points for others to make similar plots.

I noticed that you've released the code here under the LGPL-3.0 license, which is a protective/copyleft license that requires anyone reusing your code to also release their works under a GPL-family license. So as to facilitate easier reuse of portions of your code by others (and potentially libraries like MetPy), would you be willing to re-license your code with a permissive license like BSD, MIT, or Apache?

**Comment by jsillin** [comment]
Thanks for the input @jthielen. Definitely don't want to slow anyone down with license stuff I only have a vague idea about. Changed to MIT.

**Comment by jthielen** [comment]
Awesome, thanks!
