### ISSUE TITLE
Else indent off in soundingmaps.py

### ISSUE THREAD

**Issue by nluchett** [jsillin/SoundingMaps#7]
Hey Jack,

I just tried your latest version and I see that you made some changes to the else statements in soundingmaps.py. 

However, it flags the else statement in line 169 as having an incorrect indent. Instead of trying to figure out your process here, I figured I'd just post an issue. 

Would the new changes also throw off the following else statements in lines 222, and 261?

Thanks,

Nick Luchetti

**Comment by jsillin** [comment]
Hi Nick, 
Thanks for writing this up as a separate issue! I believe the 0.2.2 update I sent out yesterday should have corrected this. It is working on my end this morning. Let me know if that's not the case for you!
Jack
